version: '3'
services:
    swf:
        container_name: songwishesfordj-app
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/usr/src/app
        ports:
            - "8080:80"